### ISSUE TITLE
Invalid Landsat 7 download URL

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#11]
I was trying to download Landsat 7 images for the Harney Basin in Oregon (43/30) for 2015.  The default download URLs generated by the tool don't work for me.  If I find the corresponding image in Earth Explorer the download URLs have different "identifiers" than are listed in the code (https://github.com/dgketchum/Landsat578/blob/master/core/usgs_download.py#L88).

For example, running the tool for "LE7 2015-06-01 2015-06-30 --path 43 --row 30" will try do download the following image but return a 500 error (https://earthexplorer.usgs.gov/download/3373/LE70430302015161EDC00/STANDARD/EE).  The corresponding image in Earth Explorer for me has an identifier of 12267 (instead of 3373) and a download URL of https://earthexplorer.usgs.gov/download/12267/LE70430302015161EDC00/STANDARD/EE

First, does the original download (with 3373) work for anyone else?  I'll try some other areas and date ranges and see if I have the same issue.

**Comment by cgmorton** [comment]
Same for the first Landsat 5 image I tried (landsat LT5 2011-07-01 2011-08-01 --path 43 --row 30).
URL from Landsat578 (fails): https://earthexplorer.usgs.gov/download/3119/LT50430302011190PAC01/STANDARD/EE
URL from earth explorer (works): https://earthexplorer.usgs.gov/download/12266/LT50430302011190PAC01/STANDARD/EE

**Comment by dgketchum** [comment]
Charles this is the CLI right from pip, correct?

**Comment by cgmorton** [comment]
Yes, version 0.3.79

**Comment by dgketchum** [comment]
thx

**Comment by dgketchum** [comment]
I reproduced the error

**Comment by dgketchum** [comment]
trying to find a programmatic way of getting the identifier, assuming it will change again

**Comment by dgketchum** [comment]
I found that the mysterious 'identifier' for both LE7 and LC8 collection 1 have changed since last push.  when the search query is sent from earthexplorer (pushing 'results' button) a call is map to a google api (https://maps.googleapis.com/maps/api/js/) that probably runs a javascript app to find the the station data, then returns that as results.  this should be investigated for use, or at lease a cron test set up to identify when the identifiers change, this was the first time they have changed since I built the package
